// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZtQ_luqYg6PuXzLywzn-_nj48Z2qEqw4',
    appId: '1:374822235749:web:0f5654eb0cf51cf2e5e08c',
    messagingSenderId: '374822235749',
    projectId: 'finish-ec38e',
    authDomain: 'finish-ec38e.firebaseapp.com',
    storageBucket: 'finish-ec38e.firebasestorage.app',
    measurementId: 'G-RYNXGE7W2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkErPIBt6i5OlAQ0mrA2xPKnVjgCbVjbY',
    appId: '1:374822235749:android:edb2e268a6fa0f5fe5e08c',
    messagingSenderId: '374822235749',
    projectId: 'finish-ec38e',
    storageBucket: 'finish-ec38e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPawOjoCFqImDtqNh5uZwCIBxBLqesS7E',
    appId: '1:374822235749:ios:3eb9d9daf7b6d936e5e08c',
    messagingSenderId: '374822235749',
    projectId: 'finish-ec38e',
    storageBucket: 'finish-ec38e.firebasestorage.app',
    iosBundleId: 'com.example.myday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPawOjoCFqImDtqNh5uZwCIBxBLqesS7E',
    appId: '1:374822235749:ios:3eb9d9daf7b6d936e5e08c',
    messagingSenderId: '374822235749',
    projectId: 'finish-ec38e',
    storageBucket: 'finish-ec38e.firebasestorage.app',
    iosBundleId: 'com.example.myday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZtQ_luqYg6PuXzLywzn-_nj48Z2qEqw4',
    appId: '1:374822235749:web:c699612b90f55623e5e08c',
    messagingSenderId: '374822235749',
    projectId: 'finish-ec38e',
    authDomain: 'finish-ec38e.firebaseapp.com',
    storageBucket: 'finish-ec38e.firebasestorage.app',
    measurementId: 'G-6E34V3SYD8',
  );
}
